1HW
Necks5/afina pull request #1
Opened 2020-03-03 19:16 UTC by Necks5

первая попытка. не бейте плз

2020-03-12 13:29 UTC, blumix requested changes

2020-03-12 13:29 UTC, blumix commented on src/storage/SimpleLRU.h
> +        for(int i = 0; i < num_el; i++) {
я понимаю, что это работает, но выглядит достаточно странно, что ты берешь размер одного объекта и затем удаляешь элементы другого объекта опираясь на размер первого.

2020-03-12 13:29 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +        std::size_t new_size = value.size() - (node->second).get().value.size();
site_t не может принимать отрицательные значения. А разность может.

2020-03-12 13:29 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +            delete_last();
тут можно случайно удалить тот элемент, на который сечас указывает node

2020-03-13 17:24 UTC, xphoenix requested changes

2020-03-13 17:24 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +            std::size_t new_size = value.size() - (node->second).get().value.size();
Не работает!

2020-03-13 17:24 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +            _lru_index.insert({std::reference_wrapper<const std::string>(new_node->key), std::reference_wrapper<lru_node>(*new_node)});
Лучше сначала в список, потом в индекс

2020-03-13 17:24 UTC, xphoenix commented on src/storage/SimpleLRU.h
> +            delete_last();
```delete_last``` это overkill

2020-04-28 13:50 UTC, merged